// strings
export const SERVICE_NAME = 'ELECTRON_KAKAO';

export const CREDENTIALS_EXIST = 'CREDENTIALS_EXIST';
export const REQUEST_CREDENTIAL = 'REQUEST_CREDENTIAL';
export const WRONG_CREDENTIAL = 'WRONG_CREDENTIAL';

export const REQUEST_PASSCODE = 'REQUEST_PASSCODE';
export const WRONG_PASSCODE = 'WRONG_PASSCODE';

export const MY_INFO = 'MY_INFO';
export const CREATE_CHANNEL = 'CREATE_CHANNEL';
export const CREATE_CHANNELS = 'CREATE_CHANNELS';
export const UPDATE_CHAT_LIST = 'UPDATE_CHAT_LIST';
export const UPDATE_CHANNELS_ORDER = 'UPDATE_CHANNELS_ORDER';
export const REMOVE_CHANNEL = 'REMOVE_CHANNEL';
export const CONNECTION_LOST = 'CONNECTION_LOST';
export const LOGOUT = 'LOGOUT';

export const INCREMENTAL_FETCH_TIME = 60 * 1000; // 60 seconds
